import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import SProvider from "./components/providers/SProvider";
import "./globals.css";
import "./styles/main.scss";

const monteserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monteserrat.className}>
        <SProvider>
          {children}
        </SProvider>
      </body>
    </html>
  );
}
